// Local override maps for IVS/PUA conversion.
// This file is NOT generated by scripts and is safe for manual edits.
// - Add temporary or environment-specific patches here.
// - Entries here override generated ones in ivsCharacterMap.js.

// Example:
// export const ivsToExternalCharMap = {
//   '\uD86E\uDDE4\uDB40\uDD00': '\uXXXX' // 2B9E4_E0100 → your temporary PUA
// };

export const ivsToExternalCharMap = {
  // U+2B9E4 U+E0100 (𫧤󠄀) → provisional PUA for MJ059399
  // NOTE: Font needs regeneration to embed MJ059399 glyph at this PUA.
  //'\uD86E\uDDE4\uDB40\uDD00': '\uEEF0',
};

export const baseCharFallbackToExternalMap = {
  // Base fallback entries (IVSが続く場合は適用しないロジックは ivsUtils.js 側に実装)
  '\uD86D\uDFCB': '\uDB83\uDD35', // MJ021335
  '\uD871\uDFD3': '\uDB83\uDD58', // MJ023164
  '\u5ECA': '\uDB84\uDC4A', // MJ030184
  '\u6717': '\uDB84\uDEC1', // MJ030185
  '\u865C': '\uDB82\uDD8F', // MJ030186
  '\u6BBA': '\uDB81\uDF7D', // MJ030187
  '\u985E': '\uDB82\uDED8', // MJ030188
  '\u9686': '\uDB84\uDEF2', // MJ030189
  '\u585A': '\uDB84\uDDF5', // MJ030194
  '\u6674': '\uDB81\uDF16', // MJ030199
  '\u51DE': '\uDB84\uDF46', // MJ030205
  '\u732A': '\uDB81\uDFE3', // MJ030208
  '\u76CA': '\uDB82\uDC0F', // MJ030209
  '\u793C': '\uDB82\uDC29', // MJ030210
  '\u795E': '\uDB82\uDC35', // MJ030211
  '\u7965': '\uDB82\uDC37', // MJ030212
  '\u798F': '\uDB82\uDC3C', // MJ030213
  '\u9756': '\uDB82\uDEBA', // MJ030214
  '\u7CBE': '\uDB82\uDC78', // MJ030215
  '\u7FBD': '\uDB82\uDCA9', // MJ030216
  '\u8612': '\uDB84\uDE5C', // MJ030224
  '\u8AF8': '\uDB82\uDDDA', // MJ030226
  '\u9038': '\uDB84\uDF2E', // MJ030234
  '\u90FD': '\uDB82\uDE7A', // MJ030235
  '\u98EF': '\uDB84\uDDB4', // MJ030240
  '\u98FC': '\uDB82\uDEE2', // MJ030241
  '\u9928': '\uDB82\uDEF0', // MJ030242
  '\u9DB4': '\uDB82\uDF2A', // MJ030243
  '\u4FAE': '\uDB81\uDD9A', // MJ030244
  '\u50E7': '\uDB84\uDDDC', // MJ030245
  '\u514D': '\uDB84\uDC01', // MJ030246
  '\u52C9': '\uDB81\uDDD8', // MJ030247
  '\u52E4': '\uDB81\uDDDC', // MJ030248
  '\u5351': '\uDB81\uDDE9', // MJ030249
  '\u559D': '\uDB81\uDE0A', // MJ030250
  '\u5606': '\uDB81\uDE11', // MJ030251
  '\u5668': '\uDB81\uDE16', // MJ030252
  '\u5840': '\uDB81\uDE2D', // MJ030253
  '\u58A8': '\uDB81\uDE34', // MJ030254
  '\u5C64': '\uDB81\uDE66', // MJ030255
  '\u5C6E': '\uDB81\uDE67', // MJ030256
  '\u6094': '\uDB81\uDEB3', // MJ030257
  '\u6168': '\uDB84\uDF24', // MJ030258
  '\u618E': '\uDB81\uDEC8', // MJ030259
  '\u61F2': '\uDB84\uDE03', // MJ030260
  '\u654F': '\uDB81\uDF01', // MJ030262
  '\u65E2': '\uDB84\uDC70', // MJ030263
  '\u6691': '\uDB81\uDF1A', // MJ030264
  '\u6885': '\uDB81\uDF49', // MJ030265
  '\u6D77': '\uDB81\uDF8E', // MJ030266
  '\u6E1A': '\uDB81\uDF95', // MJ030267
  '\u6F22': '\uDB81\uDFA7', // MJ030268
  '\u716E': '\uDB81\uDFCD', // MJ030269
  '\u722B': '\uE5AA', // MJ030270
  '\u7422': '\uDB84\uDE24', // MJ030271
  '\u7891': '\uDB82\uDC23', // MJ030272
  '\u793E': '\uDB82\uDC2A', // MJ030274
  '\u7949': '\uDB82\uDC2F', // MJ030275
  '\u7948': '\uDB82\uDC2E', // MJ030276
  '\u7950': '\uDB82\uDC30', // MJ030277
  '\u7956': '\uDB82\uDC32', // MJ030278
  '\u795D': '\uDB82\uDC34', // MJ030279
  '\u798E': '\uDB82\uDC3B', // MJ030281
  '\u7BC0': '\uDB84\uDE36', // MJ030285
  '\u7DF4': '\uDB82\uDC93', // MJ030286
  '\u7E09': '\uDB82\uDC94', // MJ030287
  '\u81ED': '\uDB82\uDCDC', // MJ030291
  '\u8279': '\uDB82\uDCEA', // MJ030292
  '\u8457': '\uDB84\uDD1F', // MJ030294
  '\u8910': '\uDB82\uDDB2', // MJ030295
  '\u8996': '\uDB82\uDDC0', // MJ030296
  '\u8B01': '\uDB82\uDDDC', // MJ030297
  '\u8B39': '\uDB84\uDD5A', // MJ030298
  '\u8CD3': '\uDB82\uDDFE', // MJ030299
  '\u8D08': '\uDB82\uDE02', // MJ030301
  '\u8FB6': '\uEBC5', // MJ030302
  '\u96E3': '\uDB84\uDDA5', // MJ030304
  '\u97FF': '\uDB84\uDF34', // MJ030305
  '\u983B': '\uDB82\uDED7', // MJ030307
  '\u6075': '\uDB81\uDEB1', // MJ030308
  '\uD850\uDEEE': '\uEE88', // MJ030309
  '\u8218': '\uDB82\uDCE0', // MJ030310
  '\uD840\uDC0B': '\uDB80\uDF16', // MJ030319
  '\uD840\uDCA2': '\uEE8B', // MJ030387
  '\uD840\uDDBB': '\uDB83\uDDCB', // MJ030550
  '\uD840\uDF2B': '\uEE8C', // MJ030742
  '\uD841\uDC96': '\uDB83\uDDD3', // MJ030927
  '\uD841\uDD09': '\uEE8E', // MJ030984
  '\uD842\uDD84': '\uDB80\uDF32', // MJ031729
  '\uD842\uDED3': '\uEE93', // MJ031960
  '\uD842\uDF93': '\uDB83\uDDE1', // MJ032098
  '\uD843\uDD4A': '\uDB83\uDDE5', // MJ032337
  '\uD843\uDEDB': '\uDB83\uDDEA', // MJ032503
  '\uD844\uDE75': '\uDB83\uDDEE', // MJ032961
  '\uD844\uDEA5': '\uDB83\uDDF0', // MJ032991
  '\uD845\uDC5E': '\uDB83\uDDF5', // MJ033194
  '\uD845\uDC5F': '\uDB83\uDDF6', // MJ033196
  '\uD845\uDC6D': '\uEE97', // MJ033205
  '\uD845\uDF06': '\uEE98', // MJ033579
  '\uD846\uDCEA': '\uDB83\uDDFF', // MJ033817
  '\uD846\uDF4E': '\uDB83\uDE04', // MJ034186
  '\uD847\uDC31': '\uDB83\uDE07', // MJ034313
  '\uD847\uDDA1': '\uEE9A', // MJ034543
  '\uD847\uDF76': '\uEE9B', // MJ034827
  '\uD848\uDF1B': '\uDB83\uDE18', // MJ035471
  '\uD849\uDCED': '\uDB83\uDE1B', // MJ035828
  '\uD84A\uDC35': '\uDB83\uDE20', // MJ036334
  '\uD84A\uDC43': '\uDB83\uDE21', // MJ036351
  '\uD84C\uDF6E': '\uDB83\uDE3C', // MJ037889
  '\uD84C\uDFD2': '\uEE9F', // MJ037939
  // ... (trimmed for brevity in override; rely on generator for unlisted fallbacks)
  // Compatibility ideograph fallback (explicit): 﨎 → PUA for MJ030191
  '\uFA0E': '\uDB80\uDF11',
  '\uD86E\uDDE4': '\uEEF2', // MJ059401 base fallback when no VS
};
