// Local override maps for IVS/PUA conversion.
// This file is NOT generated by scripts and is safe for manual edits.
// - Add temporary or environment-specific patches here.
// - Entries here override generated ones in ivsCharacterMap.js.

export const ivsToExternalCharMap = {
};

export const baseCharFallbackToExternalMap = {
};
