#!/usr/bin/env python3
"""
Build external PUA-mapped font (ipa-ivs-external) from ipam.ttf using
the mapping generated by build_mapping_from_font.py (tmp/ivs_from_font.json).

This copies source glyphs by glyph name into PUA code points, then applies
metrics strategy similar to the existing pipeline.
"""
import json
import os

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
SRC_FONT = os.path.join(ROOT, 'fonts', 'ipam.ttf')
TMP_JSON = os.path.join(ROOT, 'tmp', 'ivs_from_font.json')


def js_escape_to_cp(s):
    # '\uEEF2' or '\uDB80\uDF16' → int codepoint
    if s.startswith('\\u') and len(s) == 6:
        return int(s[2:], 16)
    if s.startswith('\\u') and '\\u' in s[2:]:
        parts = s.split('\\u')[1:]
        hi = int(parts[0], 16)
        lo = int(parts[1], 16)
        return 0x10000 + ((hi - 0xD800) << 10) + (lo - 0xDC00)
    raise ValueError('Unexpected escape format: ' + s)


def main():
    try:
        import fontforge  # type: ignore
    except Exception as e:
        raise SystemExit('FontForge Python module is required: ' + str(e))

    if not os.path.exists(TMP_JSON):
        raise SystemExit('Mapping JSON not found: ' + TMP_JSON)
    with open(TMP_JSON, 'r', encoding='utf-8') as f:
        data = json.load(f)
    records = data.get('records', [])
    if not records:
        raise SystemExit('No records in mapping JSON')

    src = fontforge.open(SRC_FONT)
    ext = fontforge.font()
    ext.encoding = 'UnicodeFull'
    ext.fontname = 'IPA-IVS-External'
    ext.familyname = 'IPA-IVS-External'
    ext.fullname = 'IPA-IVS-External'
    ext.em = src.em

    copied = 0
    failed = 0
    for rec in records:
        gname = rec['glyph_name']
        pua = js_escape_to_cp(rec['pua'])
        if gname not in src:
            failed += 1
            continue
        try:
            src_glyph = src[gname]
            ext.createChar(pua)
            ext[pua].clear()
            src.selection.none()
            src.selection.select(gname)
            src.copy()
            ext.selection.none()
            ext.selection.select(pua)
            ext.paste()
            # width/vwidth
            try:
                ext[pua].width = src_glyph.width
                if hasattr(src_glyph, 'vwidth') and hasattr(ext[pua], 'vwidth'):
                    ext[pua].vwidth = getattr(src_glyph, 'vwidth', ext.em)
            except Exception:
                pass
            copied += 1
        except Exception:
            failed += 1

    # Metrics strategy (safe Win, tight Typo)
    try:
        # Copy some OS/2 metrics from source where available
        for attr in (
            'os2_weight', 'os2_width', 'os2_vendor', 'os2_fstype',
            'os2_panose', 'os2_family_class',
            'os2_typoascent', 'os2_typodescent', 'os2_typolinegap',
        ):
            if hasattr(src, attr) and hasattr(ext, attr):
                setattr(ext, attr, getattr(src, attr))
        # Tight line metrics
        if hasattr(ext, 'os2_use_typo_metrics'):
            ext.os2_use_typo_metrics = True
        try:
            ext.hhea_ascent = getattr(src, 'os2_typoascent', ext.hhea_ascent)
            ext.hhea_descent = getattr(src, 'os2_typodescent', ext.hhea_descent)
            ext.hhea_linegap = 0
        except Exception:
            pass
        # Safe Win ascent/descent based on bbox
        ymin, ymax = None, None
        for name in ext:
            try:
                g = ext[name]
                bb = g.boundingBox()
                ymin = bb[1] if ymin is None else min(ymin, bb[1])
                ymax = bb[3] if ymax is None else max(ymax, bb[3])
            except Exception:
                continue
        if ymin is not None and ymax is not None:
            if hasattr(ext, 'os2_winascent'):
                ext.os2_winascent = max(ext.os2_winascent, int(ymax)) if hasattr(ext, 'os2_winascent') else int(ymax)
            if hasattr(ext, 'os2_windescent'):
                ext.os2_windescent = max(ext.os2_windescent, int(-ymin)) if hasattr(ext, 'os2_windescent') else int(-ymin)
    except Exception:
        pass

    os.makedirs(os.path.join(ROOT, 'fonts'), exist_ok=True)
    woff2 = os.path.join(ROOT, 'fonts', 'ipa-ivs-external.woff2')
    ttf = os.path.join(ROOT, 'fonts', 'ipa-ivs-external.ttf')
    ext.generate(woff2)
    ext.generate(ttf)

    # Fix-up pass: enforce Typo metrics
    try:
        fix = fontforge.open(ttf)
        if hasattr(fix, 'os2_use_typo_metrics'):
            fix.os2_use_typo_metrics = True
        if hasattr(src, 'os2_typoascent') and hasattr(fix, 'os2_typoascent'):
            fix.os2_typoascent = int(src.os2_typoascent)
        if hasattr(src, 'os2_typodescent') and hasattr(fix, 'os2_typodescent'):
            fix.os2_typodescent = int(src.os2_typodescent)
        if hasattr(fix, 'hhea_linegap'):
            fix.hhea_linegap = 0
        fix.generate(ttf)
    except Exception:
        pass

    print(f"✓ Copied {copied} glyphs, {failed} failed")
    print(f"✓ Wrote {ttf} and {woff2}")


if __name__ == '__main__':
    main()

